// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class BoolValue {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BoolValue {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

value():boolean {
  return !!this.bb!.readInt8(this.bb_pos);
}

static sizeOf():number {
  return 1;
}

static createBoolValue(builder:flatbuffers.Builder, value: boolean):flatbuffers.Offset {
  builder.prep(1, 1);
  builder.writeInt8(+value);
  return builder.offset();
}


unpack(): BoolValueT {
  return new BoolValueT(
    this.value()
  );
}


unpackTo(_o: BoolValueT): void {
  _o.value = this.value();
}
}

export class BoolValueT {
constructor(
  public value: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return BoolValue.createBoolValue(builder,
    this.value
  );
}
}
