// automatically generated by the FlatBuffers compiler, do not modify

import { BoolValue, BoolValueT } from '../fx/bool-value';
import { ColorValue, ColorValueT } from '../fx/color-value';
import { Float2Value, Float2ValueT } from '../fx/float2value';
import { Float3Value, Float3ValueT } from '../fx/float3value';
import { Float4Value, Float4ValueT } from '../fx/float4value';
import { FloatValue, FloatValueT } from '../fx/float-value';
import { IntValue, IntValueT } from '../fx/int-value';
import { MeshValue, MeshValueT } from '../fx/mesh-value';
import { TextureValue, TextureValueT } from '../fx/texture-value';
import { UintValue, UintValueT } from '../fx/uint-value';


export enum ControlValue {
  NONE = 0,
  BoolValue = 1,
  UintValue = 2,
  IntValue = 3,
  FloatValue = 4,
  Float2Value = 5,
  Float3Value = 6,
  Float4Value = 7,
  ColorValue = 8,
  TextureValue = 9,
  MeshValue = 10
}

export function unionToControlValue(
  type: ControlValue,
  accessor: (obj:BoolValue|ColorValue|Float2Value|Float3Value|Float4Value|FloatValue|IntValue|MeshValue|TextureValue|UintValue) => BoolValue|ColorValue|Float2Value|Float3Value|Float4Value|FloatValue|IntValue|MeshValue|TextureValue|UintValue|null
): BoolValue|ColorValue|Float2Value|Float3Value|Float4Value|FloatValue|IntValue|MeshValue|TextureValue|UintValue|null {
  switch(ControlValue[type]) {
    case 'NONE': return null; 
    case 'BoolValue': return accessor(new BoolValue())! as BoolValue;
    case 'UintValue': return accessor(new UintValue())! as UintValue;
    case 'IntValue': return accessor(new IntValue())! as IntValue;
    case 'FloatValue': return accessor(new FloatValue())! as FloatValue;
    case 'Float2Value': return accessor(new Float2Value())! as Float2Value;
    case 'Float3Value': return accessor(new Float3Value())! as Float3Value;
    case 'Float4Value': return accessor(new Float4Value())! as Float4Value;
    case 'ColorValue': return accessor(new ColorValue())! as ColorValue;
    case 'TextureValue': return accessor(new TextureValue())! as TextureValue;
    case 'MeshValue': return accessor(new MeshValue())! as MeshValue;
    default: return null;
  }
}

export function unionListToControlValue(
  type: ControlValue, 
  accessor: (index: number, obj:BoolValue|ColorValue|Float2Value|Float3Value|Float4Value|FloatValue|IntValue|MeshValue|TextureValue|UintValue) => BoolValue|ColorValue|Float2Value|Float3Value|Float4Value|FloatValue|IntValue|MeshValue|TextureValue|UintValue|null, 
  index: number
): BoolValue|ColorValue|Float2Value|Float3Value|Float4Value|FloatValue|IntValue|MeshValue|TextureValue|UintValue|null {
  switch(ControlValue[type]) {
    case 'NONE': return null; 
    case 'BoolValue': return accessor(index, new BoolValue())! as BoolValue;
    case 'UintValue': return accessor(index, new UintValue())! as UintValue;
    case 'IntValue': return accessor(index, new IntValue())! as IntValue;
    case 'FloatValue': return accessor(index, new FloatValue())! as FloatValue;
    case 'Float2Value': return accessor(index, new Float2Value())! as Float2Value;
    case 'Float3Value': return accessor(index, new Float3Value())! as Float3Value;
    case 'Float4Value': return accessor(index, new Float4Value())! as Float4Value;
    case 'ColorValue': return accessor(index, new ColorValue())! as ColorValue;
    case 'TextureValue': return accessor(index, new TextureValue())! as TextureValue;
    case 'MeshValue': return accessor(index, new MeshValue())! as MeshValue;
    default: return null;
  }
}
