// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class MeshValue {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MeshValue {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMeshValue(bb:flatbuffers.ByteBuffer, obj?:MeshValue):MeshValue {
  return (obj || new MeshValue()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMeshValue(bb:flatbuffers.ByteBuffer, obj?:MeshValue):MeshValue {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MeshValue()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value():string|null
value(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
value(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startMeshValue(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, valueOffset, 0);
}

static endMeshValue(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMeshValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  MeshValue.startMeshValue(builder);
  MeshValue.addValue(builder, valueOffset);
  return MeshValue.endMeshValue(builder);
}

unpack(): MeshValueT {
  return new MeshValueT(
    this.value()
  );
}


unpackTo(_o: MeshValueT): void {
  _o.value = this.value();
}
}

export class MeshValueT {
constructor(
  public value: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const value = (this.value !== null ? builder.createString(this.value!) : 0);

  return MeshValue.createMeshValue(builder,
    value
  );
}
}
