// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { CBBundle, CBBundleT } from '../cbbundle';
import { TextureBundle, TextureBundleT } from '../texture-bundle';


export class PixelShader {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PixelShader {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPixelShader(bb:flatbuffers.ByteBuffer, obj?:PixelShader):PixelShader {
  return (obj || new PixelShader()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPixelShader(bb:flatbuffers.ByteBuffer, obj?:PixelShader):PixelShader {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PixelShader()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

crc32():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

code():string|null
code(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
code(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

entryName():string|null
entryName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
entryName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

cbuffers(index: number, obj?:CBBundle):CBBundle|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new CBBundle()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

cbuffersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

textures(index: number, obj?:TextureBundle):TextureBundle|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new TextureBundle()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

texturesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startPixelShader(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addCrc32(builder:flatbuffers.Builder, crc32:number) {
  builder.addFieldInt32(0, crc32, 0);
}

static addCode(builder:flatbuffers.Builder, codeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, codeOffset, 0);
}

static addEntryName(builder:flatbuffers.Builder, entryNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, entryNameOffset, 0);
}

static addCbuffers(builder:flatbuffers.Builder, cbuffersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, cbuffersOffset, 0);
}

static createCbuffersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCbuffersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addTextures(builder:flatbuffers.Builder, texturesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, texturesOffset, 0);
}

static createTexturesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTexturesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endPixelShader(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPixelShader(builder:flatbuffers.Builder, crc32:number, codeOffset:flatbuffers.Offset, entryNameOffset:flatbuffers.Offset, cbuffersOffset:flatbuffers.Offset, texturesOffset:flatbuffers.Offset):flatbuffers.Offset {
  PixelShader.startPixelShader(builder);
  PixelShader.addCrc32(builder, crc32);
  PixelShader.addCode(builder, codeOffset);
  PixelShader.addEntryName(builder, entryNameOffset);
  PixelShader.addCbuffers(builder, cbuffersOffset);
  PixelShader.addTextures(builder, texturesOffset);
  return PixelShader.endPixelShader(builder);
}

unpack(): PixelShaderT {
  return new PixelShaderT(
    this.crc32(),
    this.code(),
    this.entryName(),
    this.bb!.createObjList(this.cbuffers.bind(this), this.cbuffersLength()),
    this.bb!.createObjList(this.textures.bind(this), this.texturesLength())
  );
}


unpackTo(_o: PixelShaderT): void {
  _o.crc32 = this.crc32();
  _o.code = this.code();
  _o.entryName = this.entryName();
  _o.cbuffers = this.bb!.createObjList(this.cbuffers.bind(this), this.cbuffersLength());
  _o.textures = this.bb!.createObjList(this.textures.bind(this), this.texturesLength());
}
}

export class PixelShaderT {
constructor(
  public crc32: number = 0,
  public code: string|Uint8Array|null = null,
  public entryName: string|Uint8Array|null = null,
  public cbuffers: (CBBundleT)[] = [],
  public textures: (TextureBundleT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const code = (this.code !== null ? builder.createString(this.code!) : 0);
  const entryName = (this.entryName !== null ? builder.createString(this.entryName!) : 0);
  const cbuffers = PixelShader.createCbuffersVector(builder, builder.createObjectOffsetList(this.cbuffers));
  const textures = PixelShader.createTexturesVector(builder, builder.createObjectOffsetList(this.textures));

  return PixelShader.createPixelShader(builder,
    this.crc32,
    code,
    entryName,
    cbuffers,
    textures
  );
}
}
