// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class RenderState {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RenderState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRenderState(bb:flatbuffers.ByteBuffer, obj?:RenderState):RenderState {
  return (obj || new RenderState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRenderState(bb:flatbuffers.ByteBuffer, obj?:RenderState):RenderState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RenderState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

value():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startRenderState(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addType(builder:flatbuffers.Builder, type:number) {
  builder.addFieldInt32(0, type, 0);
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldInt32(1, value, 0);
}

static endRenderState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRenderState(builder:flatbuffers.Builder, type:number, value:number):flatbuffers.Offset {
  RenderState.startRenderState(builder);
  RenderState.addType(builder, type);
  RenderState.addValue(builder, value);
  return RenderState.endRenderState(builder);
}

unpack(): RenderStateT {
  return new RenderStateT(
    this.type(),
    this.value()
  );
}


unpackTo(_o: RenderStateT): void {
  _o.type = this.type();
  _o.value = this.value();
}
}

export class RenderStateT {
constructor(
  public type: number = 0,
  public value: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return RenderState.createRenderState(builder,
    this.type,
    this.value
  );
}
}
