// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { CBBundle, CBBundleT } from '../cbbundle';


export class RoutineHLSLSourceBundle {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoutineHLSLSourceBundle {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoutineHLSLSourceBundle(bb:flatbuffers.ByteBuffer, obj?:RoutineHLSLSourceBundle):RoutineHLSLSourceBundle {
  return (obj || new RoutineHLSLSourceBundle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoutineHLSLSourceBundle(bb:flatbuffers.ByteBuffer, obj?:RoutineHLSLSourceBundle):RoutineHLSLSourceBundle {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoutineHLSLSourceBundle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

code():string|null
code(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
code(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

entryName():string|null
entryName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
entryName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

cbuffers(index: number, obj?:CBBundle):CBBundle|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new CBBundle()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

cbuffersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startRoutineHLSLSourceBundle(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addCode(builder:flatbuffers.Builder, codeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, codeOffset, 0);
}

static addEntryName(builder:flatbuffers.Builder, entryNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, entryNameOffset, 0);
}

static addCbuffers(builder:flatbuffers.Builder, cbuffersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, cbuffersOffset, 0);
}

static createCbuffersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCbuffersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endRoutineHLSLSourceBundle(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRoutineHLSLSourceBundle(builder:flatbuffers.Builder, codeOffset:flatbuffers.Offset, entryNameOffset:flatbuffers.Offset, cbuffersOffset:flatbuffers.Offset):flatbuffers.Offset {
  RoutineHLSLSourceBundle.startRoutineHLSLSourceBundle(builder);
  RoutineHLSLSourceBundle.addCode(builder, codeOffset);
  RoutineHLSLSourceBundle.addEntryName(builder, entryNameOffset);
  RoutineHLSLSourceBundle.addCbuffers(builder, cbuffersOffset);
  return RoutineHLSLSourceBundle.endRoutineHLSLSourceBundle(builder);
}

unpack(): RoutineHLSLSourceBundleT {
  return new RoutineHLSLSourceBundleT(
    this.code(),
    this.entryName(),
    this.bb!.createObjList(this.cbuffers.bind(this), this.cbuffersLength())
  );
}


unpackTo(_o: RoutineHLSLSourceBundleT): void {
  _o.code = this.code();
  _o.entryName = this.entryName();
  _o.cbuffers = this.bb!.createObjList(this.cbuffers.bind(this), this.cbuffersLength());
}
}

export class RoutineHLSLSourceBundleT {
constructor(
  public code: string|Uint8Array|null = null,
  public entryName: string|Uint8Array|null = null,
  public cbuffers: (CBBundleT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const code = (this.code !== null ? builder.createString(this.code!) : 0);
  const entryName = (this.entryName !== null ? builder.createString(this.entryName!) : 0);
  const cbuffers = RoutineHLSLSourceBundle.createCbuffersVector(builder, builder.createObjectOffsetList(this.cbuffers));

  return RoutineHLSLSourceBundle.createRoutineHLSLSourceBundle(builder,
    code,
    entryName,
    cbuffers
  );
}
}
