// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ColorValue, ColorValueT } from '../fx/color-value';
import { ControlValue, unionToControlValue, unionListToControlValue } from '../fx/control-value';
import { Float2Value, Float2ValueT } from '../fx/float2value';
import { Float3Value, Float3ValueT } from '../fx/float3value';
import { Float4Value, Float4ValueT } from '../fx/float4value';
import { FloatValue, FloatValueT } from '../fx/float-value';
import { IntValue, IntValueT } from '../fx/int-value';
import { MeshValue, MeshValueT } from '../fx/mesh-value';
import { TextureValue, TextureValueT } from '../fx/texture-value';
import { UintValue, UintValueT } from '../fx/uint-value';
import { ViewTypeProperty, ViewTypePropertyT } from '../fx/view-type-property';


export class UIControl {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UIControl {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUIControl(bb:flatbuffers.ByteBuffer, obj?:UIControl):UIControl {
  return (obj || new UIControl()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUIControl(bb:flatbuffers.ByteBuffer, obj?:UIControl):UIControl {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UIControl()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

valueType():ControlValue {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ControlValue.NONE;
}

value<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

properties(index: number, obj?:ViewTypeProperty):ViewTypeProperty|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new ViewTypeProperty()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

propertiesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startUIControl(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addValueType(builder:flatbuffers.Builder, valueType:ControlValue) {
  builder.addFieldInt8(1, valueType, ControlValue.NONE);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, valueOffset, 0);
}

static addProperties(builder:flatbuffers.Builder, propertiesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, propertiesOffset, 0);
}

static createPropertiesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPropertiesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endUIControl(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUIControl(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, valueType:ControlValue, valueOffset:flatbuffers.Offset, propertiesOffset:flatbuffers.Offset):flatbuffers.Offset {
  UIControl.startUIControl(builder);
  UIControl.addName(builder, nameOffset);
  UIControl.addValueType(builder, valueType);
  UIControl.addValue(builder, valueOffset);
  UIControl.addProperties(builder, propertiesOffset);
  return UIControl.endUIControl(builder);
}

unpack(): UIControlT {
  return new UIControlT(
    this.name(),
    this.valueType(),
    (() => {
      let temp = unionToControlValue(this.valueType(), this.value.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })(),
    this.bb!.createObjList(this.properties.bind(this), this.propertiesLength())
  );
}


unpackTo(_o: UIControlT): void {
  _o.name = this.name();
  _o.valueType = this.valueType();
  _o.value = (() => {
      let temp = unionToControlValue(this.valueType(), this.value.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
  _o.properties = this.bb!.createObjList(this.properties.bind(this), this.propertiesLength());
}
}

export class UIControlT {
constructor(
  public name: string|Uint8Array|null = null,
  public valueType: ControlValue = ControlValue.NONE,
  public value: ColorValueT|Float2ValueT|Float3ValueT|Float4ValueT|FloatValueT|IntValueT|MeshValueT|TextureValueT|UintValueT|null = null,
  public properties: (ViewTypePropertyT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const value = builder.createObjectOffset(this.value);
  const properties = UIControl.createPropertiesVector(builder, builder.createObjectOffsetList(this.properties));

  return UIControl.createUIControl(builder,
    name,
    this.valueType,
    value,
    properties
  );
}
}
