export enum EAnalyzerErrors {
    SystemTypeRedefinition = 2202,
    TypeRedefinition,
    VariableRedefinition,
    SystemVariableRedefinition,
    FunctionRedifinition,
    SystemFunctionRedefinition,

    UnsupportedTypeDecl,
    UnsupportedExpr,
    UnknownVarName,
    UnknownInstruction,
    InvalidArithmeticOperation,
    InvalidArithmeticAssigmentOperation,
    InvalidAssigmentOperation,
    InvalidBitwiseOperation,
    InvalidLeftHandSideInAssignment,
    InvalidRelationalOperation,
    InvalidLogicOperation,
    InvalidConditionType ,
    InvalidConditonValueTypes,
    InvalidCastTypeUsage,
    InvalidCastTypeNotBase,
    InvalidCastUnknownType,
    InvalidUnaryOperation,
    InvalidPostfixNotArray,
    InvalidPostfixNotIntIndex,
    InvalidPostfixNotField,
    InvalidPostfixArithmetic,
    InvalidComplexNotFunction,
    InvalidComplexNotType,
    InvalidComplexNotConstructor,
    InvalidCompileNotFunction,
    InvalidCompileFunctionNotValid,
    FunctionRedefinition,
    InvalidWhileCondition,
    InvalidDoWhileCondition,
    InvalidIfCondition,
    InvalidForInitExpr,
    InvalidForInitEmptyIterator,
    InvalidForConditionEmpty,
    InvalidForConditionRelation,
    InvalidForStepEmpty,
    InvalidForStepOperator,
    InvalidForStepExpr,
    InvalidNewFieldForStructName,
    InvalidNewFieldForStructSematic,
    InvalidNewAnnotationVar,
    InvalidFunctionParameterDefenitionDefaultNeeded,
    CannotChooseFunction,
    InvalidFuncDefenitionReturnType,
    InvalidSystemFunctionReturnType,
    InvalidTypeNameNotType,
    InvalidTypeNameTemplateNotFound,
    InvalidTypeScope,
    CannotProduceType,
    InvalidTypeVectorMatrix,
    TechniqueNameRedefinition,
    InvalidFunctionRecursionNotAllowed,
    InvalidFunctionImplementationNotFound,
    // InvalidFunctionUsageVertex,
    // InvalidFunctionUsagePixel,
    FunctionIsNotCompatibleWithVertexShader,
    FunctionIsNotCompatibleWithPixelShader,
    InvalidReturnStmtVoid,
    InvalidReturnStmtEmpty,
    InvalidReturnStmtTypesNotEqual,
    InvalidFunctionReturnType,
    InvalidFunctionParameterUsage,
    InvalidTypeForWriting,
    InvalidTypeForReading,
    InvalidExprIsNotLValue,
    InvalidVariableInitializing,   // TODO: << remove (see desc below)
    InvalidVariableInitializingEx, // TODO: << remove error in favor of custom errors
    UnsupportedStateIndex,
    InvalidSamplerTexture,
    CannotCalcPadding,
    ImportedComponentNotExists,
    InvalidFunctionReturnStmtNotFound,
    UnsupportedProvideAs,
    UnreachableCode,
    OperatorCannotBeUsedWithGivenLValue, // for ex.: cannot perfom (bool4)x*=(int4)y;

    //
    //
    //

    PartFx_VertexShaderParametersMismatch,
    PartFx_InvalidSpawnStmtInitializerNotFound
};
